---
private_worker: ${PRIVATE_WORKER}
inputs:
- type: git
  branch: master
  service: ${SAMPLE_REPO}
  path: .tekton
triggers:
- type: git
  name: Trigger
  service: ${SAMPLE_REPO}
  branch: master
  events: {"push":true,"pull_request":true,"pull_request_closed":false}
  eventListener: listener
properties:
- name: DOCKER_ROOT
  value: .
  type: text
- name: DOCKER_FILE
  value: Dockerfile
  type: text 
- name: SOME_BOOL_PROP
  value: 123456
  type: SECURE
