---
private_worker: ${PRIVATE_WORKER}
inputs:
- type: git
  branch: master
  service: ${SAMPLE_REPO}
  path: .tekton
triggers:
- type: git
  name: Trigger
  service: ${SAMPLE_REPO}
  branch: master
  events: {"push":true,"pull_request":true,"pull_request_closed":false}
  eventListener: listener
properties:
- name: apikey
  value: ${API_KEY}
  type: SECURE
- name: cluster
  value: mycluster-group1-ji
  type: text 
- name: registryNamespace
  value: hhch
  type: text 
